### PR TITLE
Upcoming events

### PR DESCRIPTION
**Pull request by NataliaLKB**
https://github.com/node-girls/node-girls-website/issues/7

How it looks on the home page:

image

cc @nikhilaravi @iteles

### CODE REVIEW

**Comment by iteles** [comment]
@NataliaLKB This looks so good! :raised_hands: 

Before we merge to master for putting into production, should we update the details of the workshop? Isn't this next one building a CMS with express.js? Or did I misunderstand that?

**Comment by iteles** [comment]
Also, Nat, what do you think of adding _this_ as the second parallax image? (I have this commit ready to go if you think we should change them)

<hr/>

screen shot 2016-02-07 at 17 59 40

<hr/>

I :heart: the mealtime interactions and smiles and I think we should aim to get a few awesome mealtime shots to replace this as soon as possible, but the one we have now, all I see is 'Coca Cola' :laughing: #sopicky #sorry

<hr/>

screen shot 2016-02-07 at 17 47 09

**Comment by NataliaLKB** [comment]
@iteles I am 90% sure we agreed the next workshop was going to be Node.js again. This is to make sure we get a chance to perfect/feel comfortable with this workshop before going on to create others. @minaorangina @heron2014 can you advise?

Thanks :blush:

**Comment by NataliaLKB** [comment]
And regarding the image, please change away @iteles . If you have a commit ready, feel free to push to this branch.

Thanks so much for looking out for our branding :wink:

**Comment by heron2014** [comment]
@NataliaLKB @iteles We had couple of suggestions regards express but as I remember we have decided to dig more into Node.js before introducing new framework. Good work on event page! Looks great!

**Comment by iteles** [comment]
Thanks @NataliaLKB and @heron2014 for having WAY better memories than me! 

Added images and merging in :+1:

**Pull request merged**
