### PR TITLE
Dynamically generate events

### PR DESCRIPTION
**Pull request by minaorangina**
This PR removes the hardcoded events from `london.html` and generates them dynamically from the [`events.json` file on the json branch](https://github.com/node-girls/node-girls-website/blob/json/events.json).

If we like it, can roll out to other pages.

✨ **Bonus features** ✨ 
- Includes a link to apply to our next event if we provide `application_link` and `application_text` for that event
- If event is in the past, removes links/text about applying
- Displays a "check back soon!" message if we don't have any future events in the pipeline

Also, I removed the organisers faces - figured it wasn't really worth having anymore.

### CODE REVIEW

**Review by claireinez — COMMENTED** [review]
It looks good but I suspect it might need to be ES5-ified

**Comment by minaorangina** [comment]
@claireinez now ES5-ified :)

**Review by claireinez — APPROVED** [review]
Looks great Mina! The only thing I might add is a bit in the README about how to use it?

**Comment by minaorangina** [comment]
@claireinez added some instructions!  Please have a read and let me know if it makes sense?

**Pull request merged**
