### PR TITLE
Team page

### LINKED ISSUE #10: Meet the team page

### PR DESCRIPTION
**Pull request by nikhilaravi**
- Added team page and linked to it from the home page. 
- Added blank profile sections for organisers and mentors
- Added css for team page
- Copied over the footer and google analytics token 

Fixes #10 
## To do

I will create an issue with instructions for everyone on how to add their images and github profile links

### CODE REVIEW

**Comment by iteles** [comment]
Hooray! Nicely done for remembering the footer and GA token as well :blush: :clap: 
It looks so great, I :heart: it!

Slight point we didn't think of: seeing as we prefer the look of the node girls logo outside the nav bar, there is now no way to get back 'home' on the other page :laughing: 
Should we add a small 'node girls' logo to the far left of the nav bar for pages which are not the landing page?

cc/ @NataliaLKB

**Comment by nikhilaravi** [comment]
@iteles yes I was just about to add a comment about that!!! Yep lets add a logo to the nav bar

**Comment by iteles** [comment]
@nikhilaravi It should really be in this commit, but do we want to just get this up there so people can start adding their own photos without having to branch off a branch? #21

**Comment by nikhilaravi** [comment]
@iteles yes sure. I'm planning to tidy up the team.html page after everyone has added their images so I can add it in then.

**Comment by iteles** [comment]
👍🏻

**Pull request merged**
