### PR TITLE
adding melbourne chapter yay

### PR DESCRIPTION
**Pull request by ButenkoT**
Great news, Im adding Melbourne chapter.

Tomorrow will send separate pr with Australian events updates and upcoming events in Melbourne 5th of November and in Sydney 19th of November. It will be our last events for this year :)

@msmichellegar

### CODE REVIEW

**Comment by msmichellegar** [comment]
@ButenkoT I was just thinking about this! So excited to get this up. I'll review this evening :)

**Comment by ButenkoT** [comment]
@msmichellegar Can we have review for this one? How can I ping all participants, so whoever has time can do it?

Cheers

**Comment by msmichellegar** [comment]
Sorry, thanks for the reminder! Just had a look, merging! Exciting.

**Comment by msmichellegar** [comment]
(I'll do an update this evening to keep the "upcoming events" up to date across the site, since we have a few coming up in London and Melbourne.)

**Comment by ButenkoT** [comment]
@msmichellegar  Cool, and we have upcoming in Sydney on 19th of November

**Pull request merged**
