### PR TITLE
sydney chapter added mentors

### PR DESCRIPTION
**Pull request by ButenkoT**
Hello girls, was wondering should I do pull requests when I do changes for Sydney page or shall I push straight to master? 

Was not sure so just created a pull request :)

@msmichellegar

### CODE REVIEW

**Comment by msmichellegar** [comment]
Pull requests please! Someone will always review before pushing to master. Just nudge me or someone else from Node Girls London :)

I think there's just one more thing that needs to be done for the images to show up properly. In `style.css`, you need to assign a `background-image` for the classes you have assigned for Jessica and Reena. This is how we're pulling in the mentor/organiser images. It is in the `TEAM` section of the stylesheet. Like so:

```
.michelle {
  background-image: url("../images/team/michelle.png");
}
```

Right now it just shows up blank:

screen shot 2016-08-25 at 10 37 47 pm

I could be wrong! Let me know what you think :)

**Comment by msmichellegar** [comment]
@ButenkoT Actually I just pushed an example of the necessary changes to another branch, check them out here: https://github.com/node-girls/node-girls-website/compare/sydney-page-edition...sydney-team-images-update?expand=1

I updated the `style.css`, and removed one pair of `<div class="row">` tags from the `html` file for layout reasons.

Feel free to copy those changes over to your PR, then I'll merge! :)

**Comment by ButenkoT** [comment]
Oh nice, sure will do! thank you

**Comment by ButenkoT** [comment]
Ok, finally got time. @msmichellegar can you check up on fixes and merge if its all good? Thank you :)

**Comment by msmichellegar** [comment]
Perfect! Merging :)

**Comment by msmichellegar** [comment]
Looks so good! Thanks @ButenkoT 👍 

http://nodegirls.io/sydney

**Pull request merged**
